### ISSUE TITLE
A typo？

### ISSUE THREAD

**Issue by youngfish42** [FedML-AI/FedGraphNN#1]
For[ Installation](https://github.com/FedML-AI/FedGraphNN#installation)

`conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.1 -c pytorch -n **fedmolecule**`
The parameter ‘fedmolecule’ maybe 'fedgraphnn'

**Comment by emirceyani** [comment]
Hi,

fedmolecule was the old name of pur project, hence it was the name of anaconda environment. it's fedgraphnn.

Thanks for the catch!
