### ISSUE TITLE
error: argument --node_embedding_dim: invalid int value: '0.3'

### ISSUE THREAD

**Issue by JLU-Neal** [FedML-AI/FedGraphNN#11]
Just try to run the experiment based on the command as follow:
`sh run_fedavg_distributed_pytorch.sh 6 1 1 1 graphsage homo 150 1 1 0.0015 256 256 0.3 256 256  sider "./../../../data/sider/" 0`

**Comment by Haoran-Young** [comment]
I met the same problem because the documentation is not up-to-date, you can refer to 'run_fedavg_distributed_pytorch.sh' for precise augments description.

**Comment by JLU-Neal** [comment]
> I met the same problem because the documentation is not up-to-date, you can refer to 'run_fedavg_distributed_pytorch.sh' for precise augments description.

Yeah, I agree with you this repo is not well-maintained. I have write my own script to run the code. Thanks anyway!
