### ISSUE TITLE
Link does not work 

### ISSUE THREAD

**Issue by HamzaGbada** [FedML-AI/FedGraphNN#16]
This link for FedGraphNN does not work:
https://github.com/FedML-AI/FedML/tree/master/python/app/fedgraphnn

**Comment by kamelferrahi** [comment]
Hi, same problem, Did you found the link?

**Comment by HamzaGbada** [comment]
> Hi, same problem, Did you found the link?

Yes here is the link:
https://github.com/FedML-AI/FedML/tree/master/python/examples/federate/prebuilt_jobs/fedgraphnn
