### ISSUE TITLE
invalid value for int argument: NODE_DIM

### ISSUE THREAD

**Issue by akritikts** [FedML-AI/FedGraphNN#2]
I am trying to run the Distributed Molecule classification experiment:
sh run_fedavg_distributed_reg.sh 6 1 1 1 graphsage homo 150 1 1 0.0015 256 256 0.3 256 256 freesolv "./../../../data/freesolv/" 0

**Comment by emirceyani** [comment]
You are missing partition alpha for non-iid splitting. It should be 

`sh run_fedavg_distributed_reg.sh 6 1 1 1 graphsage homo 0.3 150 1 1 0.0015 256 256 0.3 256 256 freesolv "./../../../data/freesolv/" 0`

Please refer to this README instead: https://github.com/FedML-AI/FedGraphNN/tree/main/experiments/distributed/moleculenet . Thanks for sharing this issue. We'll update main README right now.
