### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'backend'

### ISSUE THREAD

**Issue by akritikts** [FedML-AI/FedGraphNN#3]
I'm trying to follow the classification experiments: 
From this link: https://github.com/FedML-AI/FedGraphNN/tree/main/experiments/distributed/moleculenet
This command results in the error:
sh run_fedavg_distributed_pytorch.sh 4 4 1 4 graphsage hetero 0.2 20 1 1 0.0015 64 32 0.3 64 64 sider "./../../../data/sider/" 0

**Comment by WangHui19** [comment]
I have the error too!
Have you solved it?

**Comment by ssongzoe** [comment]
you could add this line,

parser.add_argument('--backend', type=str, default='MPI', metavar='N',
                        help='idontknow')

🤔

**Comment by emirceyani** [comment]
Hi there, 
@ssongzoe thanks for the correction. we'll update the code-base in 2-3 days and you won't be facing with this error anymore.
